name: Mizumi Prod CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        script: |
          exec bash \-l
          cd ~/mizumi/backend
          git pull origin main
          git status
          yarn install
          yarn build
          cd build
          yarn install --production
          pm2 restart server

  notify-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build
    steps:
    - name: Send success alert to slack workspace
      uses: parkingboss/slackbot-postmessage@v1
      with:
        token: ${{ secrets.SLACK_SECRET }}
        request: '{"channel": "C067T5CVDQA", "text": "Prod deployment completed successfully 🚀"}'

  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: build
    steps:
    - name: Send failure alert to slack workspace
      uses: parkingboss/slackbot-postmessage@v1
      with:
        token: ${{ secrets.SLACK_SECRET }}
        request: '{"channel": "C067T5CVDQA", "text": "Prod deployment failed 😞"}'
